### ISSUE TITLE
A problem in the test script

### ISSUE THREAD

**Issue by Jensen-JZ** [zhouyuan888888/SGCPNet#2]
Well, thanks for your excellent work, but I seem to get a small problem in the process of running the test script. The details of the error report are as follows:

---

```python
$ python src/test.py
./ckpt/cityscapes.pth.tar
Traceback (most recent call last):
  File "src/test.py", line 136, in <module>
    main()
  File "src/test.py", line 80, in main
    flops_1, params_1 = profile(SGCPNet(num_classes=num_classes), inputs=(torch.randn(1, 3, 2048, 1024),))
  File "/home/jensen/workspace/Segs/SGCPNet/models/SGCPNet.py", line 9, in __init__
    mb = mbnet()
  File "/home/jensen/workspace/Segs/SGCPNet/models/mbnet.py", line 120, in mbnet
    model_dict = torch.load("/home/zhouyuan/.torch/models/mbv3_small_new.pth.tar")
  File "/home/jensen/.conda/envs/venv_torch/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jensen/.conda/envs/venv_torch/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jensen/.conda/envs/venv_torch/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhouyuan/.torch/models/mbv3_small_new.pth.tar'
```
---

According to the description of this report, it seems that the file "mbv3_small_new.pth.tar" is missing. Where should I get this file? Looking forward to your reply, thanks!

**Comment by Jensen-JZ** [comment]
> Well, thanks for your excellent work, but I seem to get a small problem in the process of running the test script. The details of the error report are as follows:
> 
> ```python
> $ python src/test.py
> ./ckpt/cityscapes.pth.tar
> Traceback (most recent call last):
>   File "src/test.py", line 136, in <module>
>     main()
>   File "src/test.py", line 80, in main
>     flops_1, params_1 = profile(SGCPNet(num_classes=num_classes), inputs=(torch.randn(1, 3, 2048, 1024),))
>   File "/home/jensen/workspace/Segs/SGCPNet/models/SGCPNet.py", line 9, in __init__
>     mb = mbnet()
>   File "/home/jensen/workspace/Segs/SGCPNet/models/mbnet.py", line 120, in mbnet
>     model_dict = torch.load("/home/zhouyuan/.torch/models/mbv3_small_new.pth.tar")
>   File "/home/jensen/.conda/envs/venv_torch/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "/home/jensen/.conda/envs/venv_torch/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "/home/jensen/.conda/envs/venv_torch/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: '/home/zhouyuan/.torch/models/mbv3_small_new.pth.tar'
> ```
> 
> According to the description of this report, it seems that the file "mbv3_small_new.pth.tar" is missing. Where should I get this file? Looking forward to your reply, thanks!

Okay, I think I've found this file. Is that [it](https://github.com/xiaolai-sqlai/mobilenetv3/blob/master/mbv3_small.pth.tar)? I have to admit that the naming of this file is confusing, hah!
